### PR TITLE
Add Tika parsed Metadata to json object

### PR DESCRIPTION
**Pull request by albertsun**
Forgive me, my java skills are really rusty.

This is basically #26 I think? Though I'm not sure if this is the right json object structure to have with S3 metadata separate from Tika extracted metadata.

### CODE REVIEW

**Comment by lbroudoux** [comment]
Hi @albertsun,

You're right : your contribution is the main part of #26. One point is that we should probably also the update the mapping definition through `S3RiverUtil.buildS3FileMapping()` by adding a `metadata` property within the `file` object.

Thank you !

**Comment by lbroudoux** [comment]
For now, I'm busy trying to migrate to ES 1.4 but will be back for merge ASAP ;-)

**Comment by albertsun** [comment]
While we're looking at this part of the code. What's the reasoning for having `title`, `file._name` and `file.title` all being the same?

**Comment by lbroudoux** [comment]
Hi @albertsun,

I finally had time to check this out and integrated your contribution to close #23. I dit not directly merge the pull request because of some other refactoring making copy/paste a lor faster.

Thank you !

**Pull request closed without merging**
